### ISSUE TITLE
sinatra/reload not reloading sequent files on docker container

### ISSUE THREAD

**Issue by Struki84** [zilverline/sequent-sinatra#17]
Hi, I was playing with sequent and following the guide https://www.sequent.io/docs/getting-started.html I managed to build the blog web application in docker. 

But while I was doing it I realised none of the sequent files would reload when I updated them and refreshed the page, all the sinatra files that were updated where refreshed. I can update the file on the host machine, it would be synced to docker, but sintra/reloader (my guess) is registering the changes only in Sinatra controllers in views. 

To updated changes on sequent files I need to restart the docker container. 

I've tried to switch to `sequent-sinatra` gem, but the problem remains. At this point I'm not sure is this a bug or not, so if needed I can provide more information. Let me know first if this is expected behaviour or not. 

EDIT: Great work btw, so far this is the best CQRS implementation in ruby I could find, I'm also a big fan of sinatra and prefer it over RoR, so that's ++ :)

**Comment by lvonk** [comment]
Hi,

First, thanks for the compliment :). So this is really a Sinatra reloading issue. This setup works for us:

```ruby
class Base < Sinatra::Base
    configure :development do
      register Sinatra::Reloader
      also_reload File.expand_path(PUT_RELATIVE_PATH_TO_LIB_FOLDER_HERE, _dir__)
   end
end
```

You can also use `dont_reload` for stuff you do not want to reload. Please let me know if this works for you.

**Comment by Struki84** [comment]
I've downloaded the sinatra web example from https://github.com/zilverline/sequent-examples, tweaked it a bit to run in docker, and added as recommended in the web.rb controller the line so it looks: 

```
class Web < Sinatra::Base
  enable :sessions
  register Sinatra::Flash

  configure :development do
    register Sinatra::Reloader
    also_reload File.expand_path("../lib", __dir__)
  end
```
Now I'm not sure if I'm putting the wrong path or smth, but I still cant get any updates on (eg. post_command_hanldler) to load on page refresh, only when I restart the docker container...

Is there any chance to show me how to get it working with your example app?

**Comment by lvonk** [comment]
Yes, I see what you mean now. The CommandHandler, with the `on` blocks are registering handlers on class level. I also experienced that with the `Sinatra::Reloader` an extra block is registered instead of replaced. This is only happens for code in the `on` blocks btw.

**Comment by Struki84** [comment]
So, to update, I didn't get it to work. The `also_reload` func is not loading any of the files, I've tried it with a simple clean sinatra only app, I was unsuccessful so I'm guessing my issue is with `Sinatra::Reloader`. If anyone comes upon the same problem, I ended up using [shotgun](https://github.com/rtomayko/shotgunl)

**Comment by Struki84** [comment]
Short update, I managed to reload sequent files using sinatra-reloader. The problem was the path I was using relative to my `lib/` folder. So the sequent lib files come in series of subfolders, 
eg. `lib/user/user_aggregate.rb`, the proper way to load all the subfolders and sequent files if you are running the app as rack app with `config.ru` in app `root`

```
configure do :development |conf|
    register Sinatra::Reloader
    conf.also_reload './lib/**/*.rb'
end
```
